# Generated by Django 3.0.8 on 2020-07-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='property_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='hello world'),
            preserve_default=False,
        ),
    ]
