# Generated by Django 3.0.8 on 2020-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200713_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='property_name',
            field=models.CharField(default='12 drivewood', max_length=120),
            preserve_default=False,
        ),
    ]
