# Generated by Django 3.0.8 on 2020-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
