# Generated by Django 3.0.8 on 2020-07-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='image',
            new_name='photo',
        ),
    ]
